FROM node:20-alpine
WORKDIR /app

COPY package*.json ./
RUN npm install --loglevel=error

COPY prisma ./prisma/
RUN npx prisma generate

COPY . ./

EXPOSE 4000
CMD npx prisma migrate deploy && npm run dev